# -*- coding: utf-8 -*-
"""chatgpt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FQSUlR0pu-mM9-3zCXpIlN0DLHXETdsk
"""

#install this library first  'pip install openai==0.28'

import openai
API_KEY = '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'
openai.api_key = API_KEY
response =openai.ChatCompletion.create(
  model = "gpt-3.5-turbo",
  messages=[
    {"role":"user", "content": "hii i am ameya.who r u?"}
  ]
)
print(response)

